packages:
  - 'packages/*'
  - 'tests'

nodeLinker: hoisted
linkWorkspacePackages: true
nodeOptions: --disable-warning=DEP0040

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  full-icu: true
  nx: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - prettier-plugin-penere
  - objection@3.3.0
