packages:
  - 'packages/*'
  - 'tests'

nodeLinker: hoisted
linkWorkspacePackages: true
nodeOptions: --disable-warning=DEP0040

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  full-icu: true
  nx: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - '@prettier/plugin-pug@3.6.0'
  - http-cache-semantics@4.3.0
  - prettier-plugin-penere
