// NOTE: index.js exports nothing, but type components will be registered in
// DitoComponent and can be retrieved through TypeComponent.get(type) and
// rendered through their component-names (e.g. dito-type-list).

import './TypeButton'
import './TypeCheckbox'
import './TypeCheckboxes'
import './TypeCode'
import './TypeColor'
import './TypeComputed'
import './TypeDate'
import './TypeList'
import './TypeMarkup'
import './TypeMultiselect'
import './TypeNumber'
import './TypeObject'
import './TypePanel'
import './TypeProgress'
import './TypeRadio'
import './TypeSection'
import './TypeSelect'
import './TypeSlider'
import './TypeSwitch'
import './TypeText'
import './TypeTextarea'
import './TypeTreeList'
import './TypeUpload'
