// NOTE: index.js exports nothing, but type components will be registered in
// DitoComponent and can be retrieved through TypeComponent.get(type) and
// rendered through their component-names (e.g. dito-type-list).

export { default as TypeButton } from './TypeButton.vue'
export { default as TypeCheckbox } from './TypeCheckbox.vue'
export { default as TypeCheckboxes } from './TypeCheckboxes.vue'
export { default as TypeCode } from './TypeCode.vue'
export { default as TypeColor } from './TypeColor.vue'
export { default as TypeComponent } from './TypeComponent.vue'
export { default as TypeComputed } from './TypeComputed.vue'
export { default as TypeDate } from './TypeDate.vue'
export { default as TypeList } from './TypeList.vue'
export { default as TypeLabel } from './TypeLabel.vue'
export { default as TypeMarkup } from './TypeMarkup.vue'
export { default as TypeMultiselect } from './TypeMultiselect.vue'
export { default as TypeNumber } from './TypeNumber.vue'
export { default as TypeObject } from './TypeObject.vue'
export { default as TypePanel } from './TypePanel.vue'
export { default as TypeProgress } from './TypeProgress.vue'
export { default as TypeRadio } from './TypeRadio.vue'
export { default as TypeSection } from './TypeSection.vue'
export { default as TypeSelect } from './TypeSelect.vue'
export { default as TypeSlider } from './TypeSlider.vue'
export { default as TypeSwitch } from './TypeSwitch.vue'
export { default as TypeText } from './TypeText.vue'
export { default as TypeTextarea } from './TypeTextarea.vue'
export { default as TypeTreeList } from './TypeTreeList.vue'
export { default as TypeUpload } from './TypeUpload.vue'
