// NOTE: index.js exports nothing, but type components will be registered in
// DitoComponent and can be retrieved through DitoTypeComponent.get(type) and
// rendered through their component-names (e.g. dito-type-list).

export { default as DitoTypeButton } from './DitoTypeButton.vue'
export { default as DitoTypeCheckbox } from './DitoTypeCheckbox.vue'
export { default as DitoTypeCheckboxes } from './DitoTypeCheckboxes.vue'
export { default as DitoTypeCode } from './DitoTypeCode.vue'
export { default as DitoTypeColor } from './DitoTypeColor.vue'
export { default as DitoDitoTypeComponent } from './DitoTypeComponent.vue'
export { default as DitoTypeComputed } from './DitoTypeComputed.vue'
export { default as DitoTypeDate } from './DitoTypeDate.vue'
export { default as DitoTypeList } from './DitoTypeList.vue'
export { default as DitoTypeLabel } from './DitoTypeLabel.vue'
export { default as DitoTypeMarkup } from './DitoTypeMarkup.vue'
export { default as DitoTypeMultiselect } from './DitoTypeMultiselect.vue'
export { default as DitoTypeNumber } from './DitoTypeNumber.vue'
export { default as DitoTypeObject } from './DitoTypeObject.vue'
export { default as DitoTypePanel } from './DitoTypePanel.vue'
export { default as DitoTypeProgress } from './DitoTypeProgress.vue'
export { default as DitoTypeRadio } from './DitoTypeRadio.vue'
export { default as DitoTypeSection } from './DitoTypeSection.vue'
export { default as DitoTypeSelect } from './DitoTypeSelect.vue'
export { default as DitoTypeSlider } from './DitoTypeSlider.vue'
export { default as DitoTypeSpacer } from './DitoTypeSpacer.vue'
export { default as DitoTypeSwitch } from './DitoTypeSwitch.vue'
export { default as DitoTypeText } from './DitoTypeText.vue'
export { default as DitoTypeTextarea } from './DitoTypeTextarea.vue'
export { default as DitoTypeTreeList } from './DitoTypeTreeList.vue'
export { default as DitoTypeUpload } from './DitoTypeUpload.vue'
